SELECT * FROM customer LIMIT 20;

-- Q1. What is the total revenue generated by male and female customers?
SELECT gender, SUM(purchase_amount) AS revenue 
FROM customer
GROUP BY gender;

-- Q2. Which customers used a discount but still spent more than the average amount?
SELECT customer_id, purchase_amount 
FROM customer
WHERE discount_applied = 'Yes' 
  AND purchase_amount > (SELECT AVG(purchase_amount) FROM customer);

-- Q3. Which are the top 5 products with the highest average review rating?
SELECT item_purchased, ROUND(AVG(review_rating::numeric), 2) AS "Average Product Rating"
FROM customer
GROUP BY item_purchased
ORDER BY AVG(review_rating) DESC
LIMIT 5;

-- Q4. Compare the average Purchase Amounts between Standard and Express Shipping.
SELECT shipping_type, ROUND(AVG(purchase_amount), 2) AS avg_purchase_amount
FROM customer
WHERE shipping_type IN ('Standard', 'Express')
GROUP BY shipping_type;

-- Q5. Do subscribed customers spend more? Compare average spend and total revenue between subscribers and non-subscribers.
SELECT subscription_status,
       COUNT(customer_id) AS total_customers,
       ROUND(AVG(purchase_amount), 2) AS avg_spend,
       ROUND(SUM(purchase_amount), 2) AS total_revenue
FROM customer
GROUP BY subscription_status
ORDER BY total_revenue DESC, avg_spend DESC;

-- Q6. Which 5 products have the highest percentage of purchases with discounts applied?
SELECT item_purchased,
       ROUND(100.0 * SUM(CASE WHEN discount_applied = 'Yes' THEN 1 ELSE 0 END) / COUNT(*), 2) AS discount_rate
FROM customer
GROUP BY item_purchased
ORDER BY discount_rate DESC
LIMIT 5;

-- Q7. Segment customers into New, Returning, and Loyal based on previous purchases, and show the count.
WITH customer_type AS (
    SELECT customer_id, previous_purchases,
           CASE 
               WHEN previous_purchases = 1 THEN 'New'
               WHEN previous_purchases BETWEEN 2 AND 10 THEN 'Returning'
               ELSE 'Loyal'
           END AS customer_segment
    FROM customer
)
SELECT customer_segment, COUNT(*) AS "Number of Customers" 
FROM customer_type 
GROUP BY customer_segment;

-- Q8. What are the top 3 most purchased products within each category?
WITH item_counts AS (
    SELECT category,
           item_purchased,
           COUNT(customer_id) AS total_orders,
           ROW_NUMBER() OVER (PARTITION BY category ORDER BY COUNT(customer_id) DESC) AS item_rank
    FROM customer
    GROUP BY category, item_purchased
)
SELECT item_rank, category, item_purchased, total_orders
FROM item_counts
WHERE item_rank <= 3;
 
-- Q9. Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?
SELECT subscription_status, COUNT(customer_id) AS repeat_buyers
FROM customer
WHERE previous_purchases > 5
GROUP BY subscription_status;

-- Q10. What is the revenue contribution of each age group?
SELECT age_group, SUM(purchase_amount) AS total_revenue
FROM customer
GROUP BY age_group
ORDER BY total_revenue DESC;

-- Q11. Which locations (states) generate the highest total revenue?
SELECT location, SUM(purchase_amount) AS total_revenue
FROM customer
GROUP BY location
ORDER BY total_revenue DESC
LIMIT 5;

-- Q12. What is the most popular payment method among subscribed vs. non-subscribed customers?
WITH ranked_payments AS (
    SELECT subscription_status, payment_method, COUNT(*) AS usage_count,
           ROW_NUMBER() OVER(PARTITION BY subscription_status ORDER BY COUNT(*) DESC) AS rank
    FROM customer
    GROUP BY subscription_status, payment_method
)
SELECT subscription_status, payment_method, usage_count
FROM ranked_payments
WHERE rank = 1;

-- Q13. How does the season affect the average purchase amount and total sales volume?
SELECT season, 
       COUNT(customer_id) AS total_sales, 
       ROUND(AVG(purchase_amount), 2) AS avg_purchase_amount
FROM customer
GROUP BY season
ORDER BY total_sales DESC;


-- Q14. Is there a correlation between the size of the item and the average review rating?
SELECT size, 
       ROUND(AVG(review_rating::numeric), 2) AS avg_review_rating, 
       COUNT(*) AS items_sold
FROM customer
GROUP BY size
ORDER BY avg_review_rating DESC;

-- Q15. Which color is the most popular in the 'Clothing' category during the 'Winter' season?
SELECT color, COUNT(*) AS times_purchased
FROM customer
WHERE category = 'Clothing' AND season = 'Winter'
GROUP BY color
ORDER BY times_purchased DESC
LIMIT 3;

-- Q16. What is the average age of customers purchasing from each product category?
SELECT category, ROUND(AVG(age), 1) AS average_age
FROM customer
GROUP BY category
ORDER BY average_age ASC;

-- Q17. Find customers who made a purchase above the overall average but left a review rating below 3.0.
SELECT customer_id, purchase_amount, review_rating
FROM customer
WHERE purchase_amount > (SELECT AVG(purchase_amount) FROM customer)
  AND review_rating < 3.0
ORDER BY purchase_amount DESC;

-- Q18. What is the total estimated revenue lost to discounts (assuming a flat 10% discount when applied)?
SELECT ROUND(SUM(purchase_amount * 0.10), 2) AS estimated_discount_cost
FROM customer
WHERE discount_applied = 'Yes';

-- Q19. Which demographic (Gender + Age Group) buys the most 'Outerwear'?
SELECT gender,
       CASE 
           WHEN age BETWEEN 18 AND 25 THEN '18-25'
           WHEN age BETWEEN 26 AND 35 THEN '26-35'
           WHEN age BETWEEN 36 AND 50 THEN '36-50'
           ELSE '50+' 
       END AS calculated_age_group,
       COUNT(*) AS total_purchases
FROM customer
WHERE category = 'Outerwear'
GROUP BY gender, calculated_age_group
ORDER BY total_purchases DESC
LIMIT 1;